### ISSUE TITLE
toplevel's node.Pos() returns wrong result

### ISSUE THREAD

**Issue by tyru** [haya14busa/go-vimlparser#44]
## Steps to reproduce

The following code prints "src.vim:1:1" to stdout but actual line number is 3.

```go
func main() {
  src := `

function! s:config()
  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
  smap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
endfunction
`
  f, _ := vimlparser.ParseFile(strings.NewReader(src), "src.vim", nil)
  fmt.Println(f.Pos()) // Prints 'src.vim:1:1'
}
```

## Cause

The following code sets wrong position to toplevel node.

https://github.com/haya14busa/go-vimlparser/blob/a3950964d5c49efc801df0e18bb02638dca2a346/go/export.go#L30-L36

## Solutions

There are several approaches (this is why I create issue not PR).

### 1. Fix go-vimlparser

```go
func main() {
  src := `


function! s:config()
  imap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
  smap <expr> <Tab> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
endfunction
`
  f, _ := vimlparser.ParseFile(strings.NewReader(src), "src.vim", nil)
  fmt.Printf("%#v\n", f)
  body := f.Body[0]
  fmt.Printf("%#v\n", body)
}
```

This outputs

```
&ast.File{Start:ast.Pos{Offset:0, Line:1, Column:1, Filename:"src.vim"}, Body:[]ast.Statement{(*ast.Function)(0xc420001200)}}
&ast.Function{Func:ast.Pos{Offset:3, Line:4, Column:1, Filename:"src.vim"}, ...(omit)... }
```

As you see, the second `ast.Function` node has correct `ast.Pos`.
You can set `ast.File`'s position from `f.Body[0].Pos()` at the end of `vimlparser.ParseFile()`.

### 2. Fix vimlparser

Add `node.pos` to also toplevel node.

@haya14busa Which solution do you prefer?

**Comment by haya14busa** [comment]
> The following code prints "src.vim:1:1" to stdout but actual line number is 3.

Isn't it expected value? `f` type is ast.File, so the position should be line 1, col 1.

**Comment by tyru** [comment]
ah, exactly.
Equivalent of toplevel node in vimlparser is ast. File (not ast.TopLevel).
The name (File) doesn't seem to require to have position.
